language: python
python:
  - "2.7"
  - "3.6"
cache: pip
before_script:
  - pip install html-testRunner
  - easy_install distribute
  - pip install -r requirements.txt
script:
  - python test_calc_online.py
branches:
  only:
    - master
